name: Index Docker images
description: Create a package SBOM for Docker images using Atomist
author: docker
branding:
  icon: anchor
  color: blue

inputs:
  image: 
    description: 'Image'
    required: true
  api-key: 
    description: 'API key'
    required: true
  workspace: 
    description: 'Workspace ID'
    required: true
runs:
  using: docker
  image: docker://atomist/docker-registry-broker:latest@sha256:9615ea5e366400c23ac9d0b08c919a92696ee7e7ad93fbd6ad3f1f446557cc00
  args:
    - index-image
    - local
    - --workspace
    - ${{ inputs.workspace }}
    - --api-key
    - ${{ inputs.api-key }}
    - --image 
    - ${{ inputs.image }}