name: Index Docker images
description: Create a package SBOM for Docker images using Atomist
author: docker
branding:
  icon: anchor
  color: blue

inputs:
  image: 
    description: 'Image'
    required: true
  api-key: 
    description: 'API key'
    required: true
  workspace: 
    description: 'Workspace ID'
    required: true
runs:
  using: docker
  image: docker://ghcr.io/cdupuis/index-cli-plugin@sha256:3166106bbcc532adc075b85ac2eaf1fcaf568528d108a96587e307095f3e5540
  env:
    ATOMIST_API_KEY: ${{ inputs.api-key }}
    ATOMIST_WORKSPACE: ${{ inputs.workspace }}
  args:
    - index
    - upload
    - --image 
    - ${{ inputs.image }}
