name: Index Docker images
description: Create a package SBOM for Docker images using Atomist
author: docker
branding:
  icon: anchor
  color: blue

inputs:
  image:
    description: "Image"
    required: true
  api-key:
    description: "API key"
    required: true
  workspace:
    description: "Workspace ID"
    required: true
runs:
  using: docker
  image: docker://atomist/docker-registry-broker:latest@sha256:9537cd4cb48ea97690bb908c86c2febe1eea17dd25ce12af7b3328c3b33edfbc
  args:
    - index-image
    - local
    - --workspace
    - ${{ inputs.workspace }}
    - --api-key
    - ${{ inputs.api-key }}
    - --image
    - ${{ inputs.image }}
