# Copyright © 2022 Atomist, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Index Docker images
description: Create a package SBOM for Docker images using Atomist
author: docker
branding:
  icon: anchor
  color: blue

inputs:
  image: 
    description: 'Image'
    required: true
  api-key: 
    description: 'API key'
    required: true
  workspace: 
    description: 'Workspace ID'
    required: true
runs:
  using: docker
  #image: docker://atomist/docker-registry-broker:latest@sha256:8a0e56b301d7882388b367cba690c5b2d87bc03b7834f72c72d67b804f0b9144
  image: Dockerfile
  args:
    - index-image
    - local
    - --workspace
    - ${{ inputs.workspace }}
    - --api-key
    - ${{ inputs.api-key }}
    - --image 
    - ${{ inputs.image }}