name: Index Docker images
description: Create a package SBOM for Docker images using Atomist
author: docker
branding:
  icon: anchor
  color: blue

inputs:
  image: 
    description: 'Image'
    required: true
  api-key: 
    description: 'API key'
    required: true
  workspace: 
    description: 'Workspace ID'
    required: true
runs:
  using: docker
  image: docker://atomist/docker-registry-broker:latest
  entrypoint:
    - "node"
    - "/usr/src/app/index.js"

  args:
    - index-image
    - local
    - --workspace
    - ${{ inputs.workspace }}
    - --api-key
    - ${{ inputs.api-key }}
    - --image 
    - ${{ inputs.image }}